-
 branches:
  only:
   - master
 version: 1.0.{build}
 build_script:
  - ps: Write-HOST "BUILD IT! " + $env:APPVEYOR_BUILD_VERSION
 test: off
 deploy_script:
  - ps: if($env:APPVEYOR_REPO_TAG){ Write-HOST "DEPLOY IT! "  $env:APPVEYOR_BUILD_VERSION}