-
 branches:
  only:
   - master
 version: 1.0.{build}
 build_script:
  - ps: Write-HOST "BUILD IT! " + $env:APPVEYOR_BUILD_VERSION
 test: off
 artifacts:
  - path: appveyor.yml
    name: npkg
 
 deploy: 
  - provider: Script
    ps: Write-Host "DEPLOY"
    on: 
     appveyor_repo_tag: false